"""add_medication_fields_to_patient_treatments

Revision ID: 18965d85fae1
Revises: add1f3ecd55c
Create Date: 2025-12-25 19:11:02.543210

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18965d85fae1"
down_revision: str | Sequence[str] | None = "add1f3ecd55c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medication_entries",
        sa.Column("patient_treatment_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "medication_entries", sa.Column("taken_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "medication_entries",
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "medication_entries", "dosage", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "medication_entries", "source", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "medication_entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_medication_entries_patient_treatment_id"),
        "medication_entries",
        ["patient_treatment_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "medication_entries",
        "patient_treatments",
        ["patient_treatment_id"],
        ["id"],
    )
    op.drop_column("medication_entries", "status")
    op.drop_column("medication_entries", "adherence_rate")
    op.drop_column("medication_entries", "frequency")
    op.drop_column("medication_entries", "mentioned_at")
    op.add_column(
        "patient_treatments",
        sa.Column("dosage", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "patient_treatments",
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "patient_treatments", sa.Column("adherence_rate", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patient_treatments", "adherence_rate")
    op.drop_column("patient_treatments", "instructions")
    op.drop_column("patient_treatments", "dosage")
    op.add_column(
        "medication_entries",
        sa.Column(
            "mentioned_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "medication_entries",
        sa.Column("frequency", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "medication_entries",
        sa.Column(
            "adherence_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "medication_entries",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "medication_entries", type_="foreignkey")
    op.drop_index(
        op.f("ix_medication_entries_patient_treatment_id"),
        table_name="medication_entries",
    )
    op.alter_column(
        "medication_entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "medication_entries", "source", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "medication_entries", "dosage", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("medication_entries", "notes")
    op.drop_column("medication_entries", "taken_at")
    op.drop_column("medication_entries", "patient_treatment_id")
    # ### end Alembic commands ###
