"""Add processing fields to CheckIn and update health entry FKs

Revision ID: 19187e95435f
Revises: 619f1bc3b8ff
Create Date: 2025-12-18 03:20:56.586279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '19187e95435f'
down_revision: Union[str, Sequence[str], None] = '619f1bc3b8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_topics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urgency_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medications_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('food_entries_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symptoms_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_medications', sa.Boolean(), nullable=False),
    sa.Column('has_nutrition', sa.Boolean(), nullable=False),
    sa.Column('has_symptoms', sa.Boolean(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_summaries_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_summaries_call_log_id'), ['call_log_id'], unique=False)

    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency_level', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'routine'"), nullable=False))
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('llm_processed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_processed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_processed')
        batch_op.drop_column('urgency_level')

    with op.batch_alter_table('call_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_summaries_call_log_id'))
        batch_op.drop_index(batch_op.f('ix_call_summaries_call_id'))

    op.drop_table('call_summaries')
    # ### end Alembic commands ###
