"""check_for_changes

Revision ID: 276e4fcedc15
Revises: 6b2dc6746355
Create Date: 2025-12-25 22:19:51.275924

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "276e4fcedc15"
down_revision: str | Sequence[str] | None = "6b2dc6746355"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medication_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "dosage",
            existing_type=sa.TEXT(),
            nullable=False,
            existing_server_default=sa.text("('')"),
        )
        batch_op.alter_column(
            "taken_at",
            existing_type=sa.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "notes",
            existing_type=sa.TEXT(),
            nullable=False,
            existing_server_default=sa.text("('')"),
        )
        batch_op.alter_column(
            "source",
            existing_type=sa.TEXT(),
            nullable=False,
            existing_server_default=sa.text("'manual'"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("patient_treatments", schema=None) as batch_op:
        batch_op.alter_column(
            "dosage",
            existing_type=sa.TEXT(),
            nullable=False,
            existing_server_default=sa.text("('')"),
        )
        batch_op.alter_column(
            "instructions",
            existing_type=sa.TEXT(),
            nullable=False,
            existing_server_default=sa.text("('')"),
        )
        batch_op.alter_column(
            "adherence_rate",
            existing_type=sa.REAL(),
            nullable=False,
            existing_server_default=sa.text("(100.0)"),
        )

    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.alter_column("severity", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("frequency", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("severity_score")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("severity_score", sa.INTEGER(), nullable=False))
        batch_op.alter_column("frequency", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("severity", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("patient_treatments", schema=None) as batch_op:
        batch_op.alter_column(
            "adherence_rate",
            existing_type=sa.REAL(),
            nullable=True,
            existing_server_default=sa.text("(100.0)"),
        )
        batch_op.alter_column(
            "instructions",
            existing_type=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("('')"),
        )
        batch_op.alter_column(
            "dosage",
            existing_type=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("('')"),
        )

    with op.batch_alter_table("medication_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "source",
            existing_type=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'manual'"),
        )
        batch_op.alter_column(
            "notes",
            existing_type=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("('')"),
        )
        batch_op.alter_column(
            "taken_at",
            existing_type=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "dosage",
            existing_type=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("('')"),
        )

    # ### end Alembic commands ###
