"""empty message

Revision ID: 619f1bc3b8ff
Revises:
Create Date: 2025-12-17 22:13:23.171572

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "619f1bc3b8ff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biomarker_aggregates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=False),
        sa.Column("patient_count", sa.Integer(), nullable=False),
        sa.Column("improvement_pct", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("biomarker_aggregates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biomarker_aggregates_period"), ["period"], unique=False
        )

    op.create_table(
        "biomarker_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("optimal_min", sa.Float(), nullable=False),
        sa.Column("optimal_max", sa.Float(), nullable=False),
        sa.Column("critical_min", sa.Float(), nullable=False),
        sa.Column("critical_max", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("biomarker_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biomarker_definitions_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_biomarker_definitions_code"), ["code"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_biomarker_definitions_name"), ["name"], unique=False
        )

    op.create_table(
        "clinic_daily_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=True),
        sa.Column("scheduled_appointments", sa.Integer(), nullable=False),
        sa.Column("walkin_appointments", sa.Integer(), nullable=False),
        sa.Column("completed_appointments", sa.Integer(), nullable=False),
        sa.Column("no_shows", sa.Integer(), nullable=False),
        sa.Column("avg_wait_time_minutes", sa.Float(), nullable=False),
        sa.Column("avg_appointment_duration_minutes", sa.Float(), nullable=False),
        sa.Column("patient_throughput", sa.Float(), nullable=False),
        sa.Column("room_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("room_occupancy_pct", sa.Float(), nullable=False),
        sa.Column("treatments_completed", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clinic_daily_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clinic_daily_metrics_date"), ["date"], unique=False
        )

    op.create_table(
        "patient_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active_patients", sa.Integer(), nullable=False),
        sa.Column("new_patients", sa.Integer(), nullable=False),
        sa.Column("total_visits", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patient_visits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patient_visits_period"), ["period"], unique=False
        )

    op.create_table(
        "treatment_protocol_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=False),
        sa.Column("avg_duration_days", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("treatment_protocol_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_treatment_protocol_metrics_name"), ["name"], unique=False
        )

    op.create_table(
        "treatments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("treatment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("treatments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_treatments_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_treatments_treatment_id"), ["treatment_id"], unique=True
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=False)

    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("treatment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("patient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("patient_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointments_appointment_id"),
            ["appointment_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_appointments_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_appointments_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "biomarker_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("biomarker_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trend", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["biomarker_id"],
            ["biomarker_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("biomarker_readings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biomarker_readings_biomarker_id"),
            ["biomarker_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_biomarker_readings_measured_at"),
            ["measured_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_biomarker_readings_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "call_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("processed_to_metrics", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("call_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_call_logs_call_id"), ["call_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_call_logs_phone_number"), ["phone_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_call_logs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("recipient_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "notification_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("patient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_notification_id"),
            ["notification_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "patient_treatments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("treatment_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sessions_completed", sa.Integer(), nullable=False),
        sa.Column("sessions_total", sa.Integer(), nullable=True),
        sa.Column("last_session_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["treatment_id"],
            ["treatments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patient_treatments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patient_treatments_treatment_id"),
            ["treatment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_patient_treatments_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "provider_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.Column("provider_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("patient_count", sa.Integer(), nullable=False),
        sa.Column("efficiency_score", sa.Float(), nullable=False),
        sa.Column("on_time_rate", sa.Float(), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("provider_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_metrics_period"), ["period"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_metrics_provider_id"), ["provider_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_metrics_provider_name"),
            ["provider_name"],
            unique=False,
        )

    op.create_table(
        "call_transcripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_log_id", sa.Integer(), nullable=False),
        sa.Column("call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_transcript", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("speaker_labels", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_log_id"],
            ["call_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("call_transcripts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_call_transcripts_call_id"), ["call_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_call_transcripts_call_log_id"), ["call_log_id"], unique=False
        )

    op.create_table(
        "checkins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("checkin_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("call_log_id", sa.Integer(), nullable=True),
        sa.Column("patient_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checkin_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("health_topics", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sentiment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("has_medications", sa.Boolean(), nullable=False),
        sa.Column("has_nutrition", sa.Boolean(), nullable=False),
        sa.Column("has_symptoms", sa.Boolean(), nullable=False),
        sa.Column("mood", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("llm_processed", sa.Boolean(), nullable=False),
        sa.Column("llm_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_log_id"],
            ["call_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checkins", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_checkins_checkin_id"), ["checkin_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_checkins_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "food_log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("checkin_id", sa.Integer(), nullable=True),
        sa.Column("call_log_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein", sa.Float(), nullable=False),
        sa.Column("carbs", sa.Float(), nullable=False),
        sa.Column("fat", sa.Float(), nullable=False),
        sa.Column("meal_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("consumed_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("logged_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_log_id"],
            ["call_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkin_id"],
            ["checkins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("food_log_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_food_log_entries_call_log_id"), ["call_log_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_food_log_entries_checkin_id"), ["checkin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_food_log_entries_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "medication_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("checkin_id", sa.Integer(), nullable=True),
        sa.Column("call_log_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dosage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("adherence_rate", sa.Float(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mentioned_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_log_id"],
            ["call_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkin_id"],
            ["checkins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medication_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medication_entries_call_log_id"),
            ["call_log_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_medication_entries_checkin_id"), ["checkin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medication_entries_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medication_entries_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "symptom_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("checkin_id", sa.Integer(), nullable=True),
        sa.Column("call_log_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity_score", sa.Integer(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trend", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reported_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_log_id"],
            ["call_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkin_id"],
            ["checkins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_symptom_entries_call_log_id"), ["call_log_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_symptom_entries_checkin_id"), ["checkin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_symptom_entries_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_symptom_entries_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_symptom_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_symptom_entries_name"))
        batch_op.drop_index(batch_op.f("ix_symptom_entries_checkin_id"))
        batch_op.drop_index(batch_op.f("ix_symptom_entries_call_log_id"))

    op.drop_table("symptom_entries")
    with op.batch_alter_table("medication_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medication_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_medication_entries_name"))
        batch_op.drop_index(batch_op.f("ix_medication_entries_checkin_id"))
        batch_op.drop_index(batch_op.f("ix_medication_entries_call_log_id"))

    op.drop_table("medication_entries")
    with op.batch_alter_table("food_log_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_food_log_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_food_log_entries_checkin_id"))
        batch_op.drop_index(batch_op.f("ix_food_log_entries_call_log_id"))

    op.drop_table("food_log_entries")
    with op.batch_alter_table("checkins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_checkins_user_id"))
        batch_op.drop_index(batch_op.f("ix_checkins_checkin_id"))

    op.drop_table("checkins")
    with op.batch_alter_table("call_transcripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_call_transcripts_call_log_id"))
        batch_op.drop_index(batch_op.f("ix_call_transcripts_call_id"))

    op.drop_table("call_transcripts")
    with op.batch_alter_table("provider_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_metrics_provider_name"))
        batch_op.drop_index(batch_op.f("ix_provider_metrics_provider_id"))
        batch_op.drop_index(batch_op.f("ix_provider_metrics_period"))

    op.drop_table("provider_metrics")
    with op.batch_alter_table("patient_treatments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_treatments_user_id"))
        batch_op.drop_index(batch_op.f("ix_patient_treatments_treatment_id"))

    op.drop_table("patient_treatments")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_notification_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("call_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_call_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_call_logs_phone_number"))
        batch_op.drop_index(batch_op.f("ix_call_logs_call_id"))

    op.drop_table("call_logs")
    with op.batch_alter_table("biomarker_readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biomarker_readings_user_id"))
        batch_op.drop_index(batch_op.f("ix_biomarker_readings_measured_at"))
        batch_op.drop_index(batch_op.f("ix_biomarker_readings_biomarker_id"))

    op.drop_table("biomarker_readings")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_user_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_date"))
        batch_op.drop_index(batch_op.f("ix_appointments_appointment_id"))

    op.drop_table("appointments")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_phone"))
        batch_op.drop_index(batch_op.f("ix_users_external_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("treatments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_treatments_treatment_id"))
        batch_op.drop_index(batch_op.f("ix_treatments_name"))

    op.drop_table("treatments")
    with op.batch_alter_table("treatment_protocol_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_treatment_protocol_metrics_name"))

    op.drop_table("treatment_protocol_metrics")
    with op.batch_alter_table("patient_visits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_visits_period"))

    op.drop_table("patient_visits")
    with op.batch_alter_table("clinic_daily_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinic_daily_metrics_date"))

    op.drop_table("clinic_daily_metrics")
    with op.batch_alter_table("biomarker_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biomarker_definitions_name"))
        batch_op.drop_index(batch_op.f("ix_biomarker_definitions_code"))
        batch_op.drop_index(batch_op.f("ix_biomarker_definitions_category"))

    op.drop_table("biomarker_definitions")
    with op.batch_alter_table("biomarker_aggregates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biomarker_aggregates_period"))

    op.drop_table("biomarker_aggregates")
    # ### end Alembic commands ###
