"""Add health data extraction tables

Revision ID: 673159062141
Revises: 
Create Date: 2025-12-11 11:03:41.495627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '673159062141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('call_log_id', sa.Integer(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['call_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_log_entries_call_log_id'), ['call_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_log_entries_summary_id'), ['summary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_log_entries_user_id'), ['user_id'], unique=False)

    op.create_table('medication_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('call_log_id', sa.Integer(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adherence_rate', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mentioned_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['call_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_entries_call_log_id'), ['call_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_entries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_entries_summary_id'), ['summary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_entries_user_id'), ['user_id'], unique=False)

    op.create_table('symptom_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('call_log_id', sa.Integer(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['call_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_entries_call_log_id'), ['call_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_entries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_entries_summary_id'), ['summary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_entries_summary_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_entries_name'))
        batch_op.drop_index(batch_op.f('ix_symptom_entries_call_log_id'))

    op.drop_table('symptom_entries')
    with op.batch_alter_table('medication_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_medication_entries_summary_id'))
        batch_op.drop_index(batch_op.f('ix_medication_entries_name'))
        batch_op.drop_index(batch_op.f('ix_medication_entries_call_log_id'))

    op.drop_table('medication_entries')
    with op.batch_alter_table('food_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_log_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_log_entries_summary_id'))
        batch_op.drop_index(batch_op.f('ix_food_log_entries_call_log_id'))

    op.drop_table('food_log_entries')
    # ### end Alembic commands ###
