"""drop_call_summaries_table

Revision ID: 6b1eecda4454
Revises: eba0a4325f60
Create Date: 2025-12-21 19:12:55.440654

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b1eecda4454"
down_revision: str | Sequence[str] | None = "eba0a4325f60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("call_summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_call_summaries_call_id"))
        batch_op.drop_index(batch_op.f("ix_call_summaries_call_log_id"))
        batch_op.drop_index(batch_op.f("ix_call_summaries_checkin_id"))

    op.drop_table("call_summaries")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_summaries",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("call_log_id", sa.INTEGER(), nullable=False),
        sa.Column("call_id", sa.VARCHAR(), nullable=False),
        sa.Column("llm_model", sa.VARCHAR(), nullable=True),
        sa.Column("processed_at", sa.DATETIME(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("checkin_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "raw_summary", sa.VARCHAR(), server_default=sa.text("('')"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["call_log_id"],
            ["call_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkin_id"], ["checkins.id"], name=op.f("fk_call_summaries_checkin_id")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("call_summaries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_call_summaries_checkin_id"), ["checkin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_call_summaries_call_log_id"), ["call_log_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_call_summaries_call_id"), ["call_id"], unique=False
        )

    # ### end Alembic commands ###
