"""empty message

Revision ID: 7d72310139c0
Revises: e0f9eb61cc21
Create Date: 2025-12-29 02:50:33.400319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d72310139c0'
down_revision: Union[str, Sequence[str], None] = 'e0f9eb61cc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Foreign key constraints already exist, no-op migration
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: No-op since upgrade is a no-op
    pass
    # ### end Alembic commands ###
