"""sync schema with models

Revision ID: a553ec7f0ddc
Revises: a86fb37edbd1
Create Date: 2025-12-28 03:59:39.531903

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a553ec7f0ddc"
down_revision: str | Sequence[str] | None = "a86fb37edbd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))

    op.drop_table("reminders")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("time", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "completed",
                sa.Boolean(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("due_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "recurring",
                sa.Boolean(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "recurrence_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_column("completed_at")
        batch_op.drop_column("recurrence_pattern")
        batch_op.drop_column("recurring")
        batch_op.drop_column("due_at")
        batch_op.drop_column("completed")
        batch_op.drop_column("time")

    op.create_table(
        "reminders",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("time", sa.VARCHAR(), nullable=False),
        sa.Column("reminder_type", sa.VARCHAR(), nullable=False),
        sa.Column("completed", sa.BOOLEAN(), nullable=False),
        sa.Column("recurring", sa.BOOLEAN(), nullable=False),
        sa.Column("recurrence_pattern", sa.VARCHAR(), nullable=True),
        sa.Column("due_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###
