"""add_condition_symptom_trend_datasource_reminder_tables

Revision ID: a86fb37edbd1
Revises: 6ac5be89f361
Create Date: 2025-12-28 01:15:21.619783

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a86fb37edbd1"
down_revision: str | Sequence[str] | None = "6ac5be89f361"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conditions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icd_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("diagnosed_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("treatments", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conditions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conditions_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conditions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("connected", sa.Boolean(), nullable=False),
        sa.Column("last_sync", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("connected_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_data_sources_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_sources_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reminder_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "recurrence_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "symptom_trends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("symptom_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_severity", sa.Integer(), nullable=False),
        sa.Column("previous_severity", sa.Integer(), nullable=False),
        sa.Column("trend", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("change_percent", sa.Float(), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("symptom_trends", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_symptom_trends_symptom_name"), ["symptom_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_symptom_trends_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("symptom_trends", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_symptom_trends_user_id"))
        batch_op.drop_index(batch_op.f("ix_symptom_trends_symptom_name"))

    op.drop_table("symptom_trends")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))

    op.drop_table("reminders")
    with op.batch_alter_table("data_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_sources_user_id"))
        batch_op.drop_index(batch_op.f("ix_data_sources_name"))

    op.drop_table("data_sources")
    with op.batch_alter_table("conditions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conditions_user_id"))
        batch_op.drop_index(batch_op.f("ix_conditions_name"))

    op.drop_table("conditions")
    # ### end Alembic commands ###
