"""empty message

Revision ID: add1f3ecd55c
Revises: e2e557389e95
Create Date: 2025-12-23 19:08:49.860746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'add1f3ecd55c'
down_revision: Union[str, Sequence[str], None] = 'e2e557389e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomarker_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarker_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarker_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_biomarker_categories_name'), ['name'], unique=False)

    op.create_table('checkin_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkin_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_checkin_types_name'), ['name'], unique=False)

    op.create_table('treatment_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatment_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_treatment_categories_name'), ['name'], unique=False)

    op.create_table('treatment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatment_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_statuses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_treatment_statuses_name'), ['name'], unique=False)

    op.create_table('urgency_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urgency_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urgency_levels_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_urgency_levels_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urgency_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urgency_levels_name'))
        batch_op.drop_index(batch_op.f('ix_urgency_levels_code'))

    op.drop_table('urgency_levels')
    with op.batch_alter_table('treatment_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_statuses_name'))
        batch_op.drop_index(batch_op.f('ix_treatment_statuses_code'))

    op.drop_table('treatment_statuses')
    with op.batch_alter_table('treatment_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_categories_name'))
        batch_op.drop_index(batch_op.f('ix_treatment_categories_code'))

    op.drop_table('treatment_categories')
    with op.batch_alter_table('checkin_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_types_name'))
        batch_op.drop_index(batch_op.f('ix_checkin_types_code'))

    op.drop_table('checkin_types')
    with op.batch_alter_table('biomarker_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarker_categories_name'))
        batch_op.drop_index(batch_op.f('ix_biomarker_categories_code'))

    op.drop_table('biomarker_categories')
    # ### end Alembic commands ###
