"""schema_sync

Revision ID: d0dab81b41cb
Revises: 276e4fcedc15
Create Date: 2025-12-25 23:38:51.395010

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0dab81b41cb"
down_revision: str | Sequence[str] | None = "276e4fcedc15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fill NULL values with defaults before making NOT NULL
    op.execute("UPDATE checkins SET sentiment = 'neutral' WHERE sentiment IS NULL")
    op.execute("UPDATE checkins SET mood = 'neutral' WHERE mood IS NULL")
    op.execute("UPDATE symptom_entries SET severity = 'mild' WHERE severity IS NULL")
    op.execute(
        "UPDATE symptom_entries SET frequency = 'occasional' WHERE frequency IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkins", schema=None) as batch_op:
        batch_op.alter_column("sentiment", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("mood", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.alter_column("severity", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("frequency", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.alter_column("frequency", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("severity", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("checkins", schema=None) as batch_op:
        batch_op.alter_column("mood", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("sentiment", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
