"""empty message

Revision ID: e0f9eb61cc21
Revises: 41e851475f81
Create Date: 2025-12-29 02:13:43.112962

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e0f9eb61cc21"
down_revision: str | Sequence[str] | None = "41e851475f81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Skipping drop_constraint(None) - constraints already properly set up
    # Only create foreign keys if they don't exist
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: No-op since upgrade is a no-op
    pass
    # ### end Alembic commands ###
