"""remove_has_fields_from_checkin

Revision ID: e2e557389e95
Revises: 6b1eecda4454
Create Date: 2025-12-21 23:29:31.769284

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2e557389e95"
down_revision: str | Sequence[str] | None = "6b1eecda4454"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema: Remove has_medications, has_nutrition, has_symptoms from checkins.

    These boolean flag fields are redundant - presence of health data can be
    determined by checking if related entries exist in medication_entries,
    food_log_entries, and symptom_entries tables.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkins", schema=None) as batch_op:
        batch_op.drop_column("has_symptoms")
        batch_op.drop_column("has_nutrition")
        batch_op.drop_column("has_medications")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Re-add has_* boolean flag fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkins", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "has_medications", sa.BOOLEAN(), nullable=False, server_default="0"
            )
        )
        batch_op.add_column(
            sa.Column("has_nutrition", sa.BOOLEAN(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("has_symptoms", sa.BOOLEAN(), nullable=False, server_default="0")
        )
    # ### end Alembic commands ###
