"""slim_callsummary_remove_redundant_fks

Revision ID: eba0a4325f60
Revises: 19187e95435f
Create Date: 2025-12-21 17:56:04.804955

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eba0a4325f60"
down_revision: str | Sequence[str] | None = "19187e95435f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("call_summaries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("checkin_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "raw_summary",
                sqlmodel.sql.sqltypes.AutoString(),
                server_default=sa.text("('')"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_call_summaries_checkin_id"), ["checkin_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_call_summaries_checkin_id", "checkins", ["checkin_id"], ["id"]
        )
        batch_op.drop_column("health_topics")
        batch_op.drop_column("symptoms_json")
        batch_op.drop_column("has_nutrition")
        batch_op.drop_column("urgency_level")
        batch_op.drop_column("food_entries_json")
        batch_op.drop_column("medications_json")
        batch_op.drop_column("has_medications")
        batch_op.drop_column("sentiment")
        batch_op.drop_column("summary")
        batch_op.drop_column("has_symptoms")

    with op.batch_alter_table("food_log_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_food_log_entries_call_log_id"))
        batch_op.drop_column("call_log_id")

    with op.batch_alter_table("medication_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medication_entries_call_log_id"))
        batch_op.drop_column("call_log_id")

    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_symptom_entries_call_log_id"))
        batch_op.drop_column("call_log_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("symptom_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("call_log_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_symptom_entries_call_log_id", "call_logs", ["call_log_id"], ["id"]
        )
        batch_op.create_index(
            batch_op.f("ix_symptom_entries_call_log_id"), ["call_log_id"], unique=False
        )

    with op.batch_alter_table("medication_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("call_log_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_medication_entries_call_log_id", "call_logs", ["call_log_id"], ["id"]
        )
        batch_op.create_index(
            batch_op.f("ix_medication_entries_call_log_id"),
            ["call_log_id"],
            unique=False,
        )

    with op.batch_alter_table("food_log_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("call_log_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_food_log_entries_call_log_id", "call_logs", ["call_log_id"], ["id"]
        )
        batch_op.create_index(
            batch_op.f("ix_food_log_entries_call_log_id"), ["call_log_id"], unique=False
        )

    with op.batch_alter_table("call_summaries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "has_symptoms",
                sa.BOOLEAN(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "summary", sa.VARCHAR(), server_default=sa.text("('')"), nullable=False
            )
        )
        batch_op.add_column(sa.Column("sentiment", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "has_medications",
                sa.BOOLEAN(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("medications_json", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("food_entries_json", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "urgency_level",
                sa.VARCHAR(),
                server_default=sa.text("('routine')"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_nutrition",
                sa.BOOLEAN(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("symptoms_json", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("health_topics", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("fk_call_summaries_checkin_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_call_summaries_checkin_id"))
        batch_op.drop_column("raw_summary")
        batch_op.drop_column("checkin_id")

    # ### end Alembic commands ###
